from typing import Protocol

from api.domain.aggregates.asset import Asset
from api.domain.aggregates.guide import Guide


class IAssetRepository(Protocol):
    async def get(self, *, id: str) -> Asset: ...
    async def list(self) -> list[Asset]: ...
    async def save(self, *, asset: Asset) -> None: ...
    async def delete(self, *, id: str) -> None: ...


class IGuideRepository(Protocol):
    async def get(self, *, id: str) -> Guide: ...
    async def list(self) -> list[Guide]: ...
    async def save(self, *, guide: Guide) -> None: ...
    async def delete(self, *, id: str) -> None: ...
