from typing import Protocol

from api.domain.aggregates.asset.aggregate import Asset


class IAssetRepository(Protocol):
    async def get(self, *, id: str) -> Asset: ...
    async def list(self) -> list[Asset]: ...
    async def save(self, *, asset: Asset) -> None: ...
    async def delete(self, *, id: str) -> None: ...
